require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ExposuresController, :type => :controller do

  # This should return the minimal set of attributes required to create a valid
  # Exposure. As you add validations to Exposure, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    {summary: "MyString",
    published: "MyString",
    cvss_severity: 1,
    title: "MyString",
    cvss_v2_base_score: 1,
    impact_subscore: 1,
    exploitability_subscore: 1,
    access_vector: "MyString",
    access_complexity: "MyString",
    authentication: "MyString",
    impact_type: "MyString",
    web_link: "MyString",
    external_source_organization: "MyString",
    external_source_name: "MyString",
    external_source_link: "MyString"}
  }

  let(:invalid_attributes) {
    {summary: 1,
    published: "MyString",
    cvss_severity: 1,
    title: "MyString",
    cvss_v2_base_score: 1,
    impact_subscore: 1,
    exploitability_subscore: 1,
    access_vector: "MyString",
    access_complexity: "MyString",
    authentication: "MyString",
    impact_type: "MyString",
    web_link: "MyString",
    external_source_organization: "MyString",
    external_source_name: "MyString",
    external_source_link: "MyString"}
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ExposuresController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all exposures as @exposures" do
      exposure = Exposure.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:exposures)).to eq([exposure])
    end
  end

  describe "GET show" do
    it "assigns the requested exposure as @exposure" do
      exposure = Exposure.create! valid_attributes
      get :show, {:id => exposure.to_param}, valid_session
      expect(assigns(:exposure)).to eq(exposure)
    end
  end

  describe "GET new" do
    it "assigns a new exposure as @exposure" do
      get :new, {}, valid_session
      expect(assigns(:exposure)).to be_a_new(Exposure)
    end
  end

  describe "GET edit" do
    it "assigns the requested exposure as @exposure" do
      exposure = Exposure.create! valid_attributes
      get :edit, {:id => exposure.to_param}, valid_session
      expect(assigns(:exposure)).to eq(exposure)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Exposure" do
        expect {
          post :create, {:exposure => valid_attributes}, valid_session
        }.to change(Exposure, :count).by(1)
      end

      it "assigns a newly created exposure as @exposure" do
        post :create, {:exposure => valid_attributes}, valid_session
        expect(assigns(:exposure)).to be_a(Exposure)
        expect(assigns(:exposure)).to be_persisted
      end

      it "redirects to the created exposure" do
        post :create, {:exposure => valid_attributes}, valid_session
        expect(response).to redirect_to(Exposure.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved exposure as @exposure" do
        post :create, {:exposure => invalid_attributes}, valid_session
        expect(assigns(:exposure)).to be_a_new(Exposure)
      end

      it "re-renders the 'new' template" do
        post :create, {:exposure => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      let(:new_attributes) {
        {summary: "UpdatedString",
         published: "UpdatedString",
         cvss_severity: 1,
         title: "UpdatedString",
         cvss_v2_base_score: 1,
         impact_subscore: 1,
         exploitability_subscore: 1,
         access_vector: "UpdatedString",
         access_complexity: "UpdatedString",
         authentication: "UpdatedString",
         impact_type: "UpdatedString",
         web_link: "UpdatedString",
         external_source_organization: "UpdatedString",
         external_source_name: "UpdatedString",
         external_source_link: "UpdatedString"}
      }

      it "updates the requested exposure" do
        exposure = Exposure.create! valid_attributes
        put :update, {:id => exposure.to_param, :exposure => new_attributes}, valid_session
        exposure.reload
      end

      it "assigns the requested exposure as @exposure" do
        exposure = Exposure.create! valid_attributes
        put :update, {:id => exposure.to_param, :exposure => valid_attributes}, valid_session
        expect(assigns(:exposure)).to eq(exposure)
      end

      it "redirects to the exposure" do
        exposure = Exposure.create! valid_attributes
        put :update, {:id => exposure.to_param, :exposure => valid_attributes}, valid_session
        expect(response).to redirect_to(exposure)
      end
    end

    describe "with invalid params" do
      it "assigns the exposure as @exposure" do
        exposure = Exposure.create! valid_attributes
        put :update, {:id => exposure.to_param, :exposure => invalid_attributes}, valid_session
        expect(assigns(:exposure)).to eq(exposure)
      end

      it "re-renders the 'edit' template" do
        exposure = Exposure.create! valid_attributes
        put :update, {:id => exposure.to_param, :exposure => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested exposure" do
      exposure = Exposure.create! valid_attributes
      expect {
        delete :destroy, {:id => exposure.to_param}, valid_session
      }.to change(Exposure, :count).by(-1)
    end

    it "redirects to the exposures list" do
      exposure = Exposure.create! valid_attributes
      delete :destroy, {:id => exposure.to_param}, valid_session
      expect(response).to redirect_to(exposures_url)
    end
  end

end
